version: '3.2'
# Add custom env files `.*_env` based on `dot_*_env` model
services:
  web:
    build:
      context: ./.
      dockerfile: Dockerfile
    links:
      - database
    ports:
      - "127.0.0.1:8888:80"
    volumes:
      - ./images:/var/www/html/images
      - ./assets:/var/www/html/resources/assets
      # May be commented-out for the first container build (as entrypoint.sh first expects it to be absent)
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
    restart: always
    env_file: .mw_env
    depends_on:
      - database
  database:
    # Higher version require to set MYSQL_ROOT_PASSWORD, rather than MYSQL_USER, MYSQL_PASSWORD
    # see https://hub.docker.com/_/mariadb
    image: mariadb:10.5.6
    volumes:
      - database:/var/lib/mysql
    restart: always
    env_file: .db_env
volumes:
  database:
