version: '3.2'
# Add a custom env files `.*_env` based on `dot_*_env` model
services:
  web:
    build:
      context: ./.
      dockerfile: Dockerfile
    container_name: inventaire-mediawiki_web
    links:
      - database
    ports:
      - "127.0.0.1:8888:80"
    volumes:
      - images:/var/www/html/images
    restart: always
    env_file:
      - .db_env
      - .mw_env
  database:
    image: mariadb
    container_name: inventaire-mediawiki_mariadb
    volumes:
      - database:/var/lib/mysql
    restart: always
    env_file: .db_env
volumes:
  images:
  database:
